### ISSUE TITLE
Commanding motors to stop should clear homing flags

### ISSUE THREAD

**Issue by JulianOrteil** [ponoor/step-series-support#11]
@kanta 

If I command the controller to stop the motors while they are homing (via ``/hardHiz``, for example), I am unable to restart their homing processes.
Output from ``/getHiZ`` and ``/getHomingStatus`` when trying to restart their homing:
```HiZ(address='/HiZ', motorID=2, state=True)```
```HomingStatus(address='/homingStatus', motorID=2, homingStatus=1)```

Due to the large nature of my project, waiting for timeout from GoUntil or ReleaseSw is not practical.

Thanks,
Jules

**Comment by kanta** [comment]
@JulianOrteil Thank you for pointing this out, obviously this is a problem of the firmware. I will update it.
Thanks!

**Comment by JulianOrteil** [comment]
@kanta Apologies. I believe this is also the case when homing is interrupted by any command like ``/goto``.

**Comment by kanta** [comment]
@JulianOrteil Ah you are right, I've never tried it but it should be happen. I will check the behavior with a physical machine in Monday. Thank you!

By the way, I am trying to combine the firmware of STEP400 and STEP800.
https://github.com/ponoor/step-series-universal-firmware
I should work same as original firmware but I have not tested whole commands. I believe your test code from the Python library  will be the perfect tool for that purpose. I still have a problem for basic usage so let me have a question about it at the library's issue in next week!

**Comment by JulianOrteil** [comment]
Sure!

And no problem! I haven't finished documentation on how to properly run tests on the library and need to change a couple things, but let me know any questions you have.

I'll close this ticket once you have updated the firmware.

Thanks :)
Jules
________________________________

**Comment by kanta** [comment]
Thank you, it will be great help to me!

About homing status, I have updated the firmware for both STEPP400 and 800. 
https://github.com/ponoor/STEP400
https://github.com/ponoor/STEP800

I realize that only `/run` can interrupt a homing, and other motion commands (`/goTo`, `/move`, etc...) will be ignored and cause the error `CommandIgnored`. This behavior is inherited from the motor driver chip. 
So following commands will interrupt to homing.
- `/run`
- `/hardHiZ`
- `/hardStop`
- `/softHiZ` 
- `/softStop`

If the electromagnetic brake is enabled,
- [`/activate`](https://ponoor.com/en/docs/step-series/osc-command-reference/brake/#activate_intmotorid_boolstate)
- [`/free`](https://ponoor.com/en/docs/step-series/osc-command-reference/brake/#free_intmotorid)

activate is bit complicated. `/activate (int)motorID (bool)state` switches motor energize and release(HiZ). Homing will be interrupted when the motor is released. You can not start homing before energize the motor so there is no condition to send enable message during homing. 

Anyway lots of overlooked bugs found, thanks!!

**Comment by JulianOrteil** [comment]
@kanta Thank you very much for your work. I was wondering though, for ``/goTo`` and ``/move``, could you send a ``/run`` command internally before executing ``/goTo`` and ``/move`` as a work around? Consider the following logic plan:

``user calls /goTo -> /goTo checks if we are homing -> if yes, /goTo calls '/run 0' -> /goTo executes normally``

That plan would then apply to ``/move`` or other motion commands.

Just a thought :)

**Comment by kanta** [comment]
That's a brilliant idea! It should work for the homing, also cascading some `/goTo` should be possible with this technique. 
`/move` is executable when the motor is stopped, so probably only `/goTo` will work.

I will try them out and come back.

BTW I found a mistake in the doc, `/goTo` and `/goToDir` are executable when not in BUSY state but they were described as "Always". I have fixed it.
https://ponoor.com/en/docs/step-series/osc-command-reference/motor-control/#goto_intmotorid_intposition

**Comment by JulianOrteil** [comment]
Oh, I also thought. To work around the issues still imposed by ``/move``, perhaps sending ``/softStop`` or ``/softHiZ`` would be better than ``/run 0``? I would think all three are essentially the same?

Your testing will tell us though!

**Comment by JulianOrteil** [comment]
@kanta I was able to successfully test the changes you made. They appear to work! Thanks!

**Comment by kanta** [comment]
@JulianOrteil Thanks for the test!
Some follow ups. 
Sending `/run` internally before `/goTo` works! This works for a homing and positioning commands as well. For example, `/goTo` can be sent during executing another `/goTo`. `/goToDir`, `/goHome`, and `/goMark` work same. If the new command specifies the same direction of the current command, the motion will be connected seamlessly. For the opposite direction, the motion will be stopped once then start the new motion again. 
For `/move`, the motion have to stop once even the same direction command. I think it's not natural and not useful so I haven't implemented this overwrite function.

These new functionalities are implemented only in the "universal version" so far.
https://github.com/ponoor/step-series-universal-firmware

I couldn't find a time to work for a validating environment for the new firmware in these days but will start soon!

**Comment by JulianOrteil** [comment]
@kanta Glad to hear it! These are definitely beneficial improvements and changes, and I will definitely be taking advantage of them.

On a personal note, the company I work for has taken an interest to your controllers and may be looking at ordering some in the future. I'll let you know if and when they make that decision :)

Jules

**Comment by kanta** [comment]
@JulianOrteil That's awesome, thanks Julien!
And thank you too for your great idea!
